### ISSUE TITLE
Option for limiting emails?

### ISSUE THREAD

**Issue by vmcilwain** [smartinez87/exception_notification#106]
I was looking through the code but didn't see anything about this so I thought I would ask. Is there a way to limit the number of emails sent based on a time stamp or a counter or something? THe idea is to throttle the email in the event that several thousand get triggered for the same error.

**Comment by ruslansavenok** [comment]
The logic of monkey path described above could be implemented in `config.ignore_if` block. 

But if you're using multi-thread server like puma, timestamp in variable approach would limit only that thread instead of entire app. I managed to solve that by storing timestamp in redis.

**Comment by Eric-Guo** [comment]
@ruslansavenok can you show how to add time limit in config.ignore_if in code?

**Comment by solars** [comment]
+1

**Comment by Skulli** [comment]
@Eric-Guo try something like https://gist.github.com/Skulli/80a3f31d1b25b7b98c025b2bd182aa4a

I did not use timestamps but you could do that as well when you store it as value instead.

**Comment by FLarra** [comment]
Closing this issue since I consider it resolved due to:

1. @jlxw monkey patch suggested
2. @Skulli ignore_if approach
3. We have an official way to handle that: https://github.com/smartinez87/exception_notification#error-grouping
