### ISSUE TITLE
ignore_exceptions doesn' t work 

### ISSUE THREAD

**Issue by dfang** [smartinez87/exception_notification#136]
i added this to my config 
:ignore_exceptions  => ['ActionView::MissingTemplate', 'Mongoid::Errors::DocumentNotFound'] + ExceptionNotifier.default_ignore_exceptions

but i still got emails titled "ActionView::MissingTemplate" and  "Mongoid::Errors::DocumentNotFound"

rails: 3.2.13
exception_notification: ~> 3.0.0'

any ideas ?

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by jalada** [comment]
I'm not using `exception_notification` anymore, so I can't test to see if this still applies.

**Comment by monfresh** [comment]
I'm still seeing this in 4.2.2, but reading the earlier comments, it sounds like you can't ignore a subset of errors from background jobs? The suggestion above was to remove `require 'exception_notification/sidekiq'` from the intializer, but won't that completely ignore **all** errors from background jobs?

I want to receive all errors from background jobs, except for some specific errors, like `Twilio::REST::RestError`. Is this not possible?

**Comment by EmilioCristalli** [comment]
@monfresh what version of sidekiq are you using?

If you remove `require 'exception_notification/sidekiq'` it will completely stop notifications from sidekiq.

Looking at the code I think the ignore exceptions option should work from sidekiq. 
Can you share a minimal app to reproduce the issue with sidekiq?

**Comment by monfresh** [comment]
@EmilioCristalli I'm not using this gem anymore at my current job, so I won't have time to share a minimal app. In my previous job, we eventually stopped using Sidekiq altogether so this wasn't an issue for us anymore.

**Comment by EmilioCristalli** [comment]
:+1:

@dfang @swathik are you still having this issue? What version of sidekiq are you using?

**Comment by macmartine** [comment]
This is not working for me either:
Version 4.4.0
Sidekiq 6.0.6

initializer:
```
config.add_notifier :email, { 
   ignore_if: ->(env, exception) { exception.message =~ /IGNORE/  }, 
  :email_prefix => "[ERROR] ",   
  :sender_address => %{"Notifier" <noreply@mydomain.com>},
  exception_recipients => %w{email@mydomain.com} 
}  
```
Error triggered:

raise("IGNORE: Bad token")

Triggering this error in Sidekiq still sends email.
