### ISSUE TITLE
uninitialized constant ExceptionNotification (NameError)

### ISSUE THREAD

**Issue by pencilcheck** [smartinez87/exception_notification#164]
I bundled gem and get 3.0.1 and put in the configuration as said on the README

Whatever::Application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :email_prefix => "[Whatever] ",
    :sender_address => %{"notifier" notifier@example.com},
    :exception_recipients => %w{exceptions@example.com}
  }

And when I start the rails app I see this error. I wonder if README is updated for the stable version or is it for the beta version? I saw the branches, but I am not sure if branch "2-3-stable" is the one I am looking for...

**Comment by bretweinraub** [comment]
yup .... exactly.
