### ISSUE TITLE
Email notifier via SMTP does not work unless SMTP settings are defined under middleware

### ISSUE THREAD

**Issue by sl4m** [smartinez87/exception_notification#186]
```
Version 4.0.0
Rails 4.0.0
```

```
Note: I wanted to investigate this further and create a PR, but I don't know if I have enough time - creating an issue for now
```

I ran into this issue last week when configuring this gem for our staging/production environments. I initially set up `action_mailer` in the config file as follows:

```
Test::Application.configure do
  config.action_mailer.delivery_method         = :smtp
  config.action_mailer.smtp_settings           = {
    address:          'smtp.host.com',
    port:                587,
    user_name:      'user_name',
    password:        'password',
    authentication: 'plain',
    enable_starttls_auto: true
  }
end
```

When I intentionally raised an exception in the application, this gem appeared in the log:

```
An error occurred when sending a notification using 'email' notifier. Errno::ECONNREFUSED: Connection refused - connect(2)
```

I finally decided to try the specific `smtp_settings` in the `email` hash and it started working:

```
Test::Application.configure do
   config.middleware.use ExceptionNotification::Rack, email: {
     email_prefix:         '[Error on staging] ',
     exception_recipients: 'recipient@example.com',
     sender_address:       'no-reply@example.com'
    delivery_method:      :smtp,
    smtp_settings: {
      address:                   'smtp.host.com',
      port:                         587,
      user_name:               'user_name',
      password:                 'password',
      authentication:          :plain,
      enable_starttls_auto: true
    }
end
```

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by scottswezey** [comment]
Unfortunately, I no longer have this gem in production. Thus I won't be able to help test or reproduce.

Thanks for your work and good luck with bug squashing.
