### ISSUE TITLE
Delayed::Job Notification

### ISSUE THREAD

**Issue by tomrossi7** [smartinez87/exception_notification#195]
Can anyone point me to better instructions for sending out exception notifications when delayed::jobs fail?  I can't seem to get it to work on Rails 4 following an approach similar to:

http://stackoverflow.com/questions/5972903/how-to-make-exceptionnotifier-work-with-delayed-job-in-rails-3

I've also posted this issue here:

http://stackoverflow.com/questions/18777746/configuring-exception-notification-with-delayed-jobs-in-rails-4

**Comment by vedant1811** [comment]
I am using @lucerion's method, but I am getting the same (useless framework) trace. I just get notified about the error. No details I get.
Mail and implementation: https://gist.github.com/vedant1811/4cb391c4151b07310bed

**Comment by micred** [comment]
To get notified only at the last attempt I added ` if job.attempts == Delayed::Worker.max_attempts` to the original code of @lucerion .

The full fledged notification code (improved by from http://stackoverflow.com/a/6967915/930720) is:

    # Optional but recommended for less future surprises.
    # Fail at startup if method does not exist instead of later in a background job
    [[ExceptionNotifier::Notifier, :background_exception_notification]].each do |object, method_name|
      raise NoMethodError, "undefined method `#{method_name}' for #{object.inspect}" unless object.respond_to?(method_name, true)
    end
    
    # Chain delayed job's handle_failed_job method to do exception notification
    Delayed::Worker.class_eval do
      def handle_failed_job_with_notification(job, error)
        handle_failed_job_without_notification(job, error)
        # rescue if ExceptionNotifier fails for some reason
        begin
          ExceptionNotifier.notify_exception(error)  if job.attempts == Delayed::Worker.max_attempts
        rescue Exception => e
          Rails.logger.error "ExceptionNotifier failed: #{e.class.name}: #{e.message}"
          e.backtrace.each do |f|
            Rails.logger.error "  #{f}"
          end
          Rails.logger.flush
        end
      end
      alias_method_chain :handle_failed_job, :notification
    end

**Comment by akaspick** [comment]
For Rails 5+

```
# in config/initializers/delayed_job.rb
module CustomFailedJob
  def handle_failed_job(job, error)
    super
    ExceptionNotifier.notify_exception(error, data: {job: job})
  end
end

class Delayed::Worker
  prepend CustomFailedJob
end
```

**Comment by massens** [comment]
And to send it only on the last attempt for Rails +5: 

```
# Send emails with exceptions
module CustomFailedJob
  def handle_failed_job(job, error)
    super
    if job.attempts == Delayed::Worker.max_attempts
      ExceptionNotifier.notify_exception(error, data: {job: job})
    end
  end
end

class Delayed::Worker
  prepend CustomFailedJob
end
```

**Comment by richhollis** [comment]
In case it helps anyone else that finds this through google, I've found this works well for me.

From https://stackoverflow.com/questions/5972903/how-to-make-exceptionnotifier-work-with-delayed-job-in-rails-3

```
class DelayedJobExceptionNotification < Delayed::Plugin
  callbacks do |lifecycle|
    lifecycle.around(:invoke_job) do |job, *args, &block|
      begin
        block.call(job, *args)
      rescue StandardError => error
        ExceptionNotifier.notify_exception(error, data: {job: job})
        raise error
      end
    end
  end
end

Delayed::Worker.plugins << DelayedJobExceptionNotification
```
