### ISSUE TITLE
Variables exposed to ignore_if other than the exception variable.

### ISSUE THREAD

**Issue by jtorresGW** [smartinez87/exception_notification#209]
This may not be the correct area to post this. Let me know if there is a more suitable place for questions/requests.

Aside from the environment and the exception itself, are there any other variables available to use with the ignore_if option when ignoring exceptions? Like:  backtrace, kontroller, sections, ...etc.
This goes along the line of ignoring an exception depending on the finding of a particular string within one of these variables.

**Comment by EmilioCristalli** [comment]
hi @jtorresGW 
the ignore conditions receive both the exception and the options passed to `notify_exception` (https://github.com/smartinez87/exception_notification/blob/3fe9f9bd9c867a4f00d1faa4ceda68bd8ea4c445/lib/exception_notifier.rb#L105)

Options usually include the `env` (at least when the notification is triggered by the rack middleware), so you should be able to access the request, controller, etc. 

These are the same params passed to each notifier (https://github.com/smartinez87/exception_notification/blob/3fe9f9bd9c867a4f00d1faa4ceda68bd8ea4c445/lib/exception_notifier.rb#L105) so you should have access to pretty much everything the notifier has (except for options provided on the initializer).

Is there anything in particular you need to have access to but you are not being able to?
