### ISSUE TITLE
ActionController::Live exceptions not caught

### ISSUE THREAD

**Issue by botandrose** [smartinez87/exception_notification#215]
Howdy! Recently I noticed that any exceptions generated while streaming via AC::Live in Rails 4 are not caught by ExceptionNotification, nor does the user receive any indication that anything has gone wrong... the output from the Rails server just ceases. Makes it easy for errors to hide!

Anyhow, I added this to an initializer, and I'm receiving notifications again:

``` ruby
ActionController::Live.class_eval do
  def log_error(exception)
    ExceptionNotifier.notify_exception(exception, env: request.env)
    super
  end
end
```

However, I'm thinking we probably should bake this into the Railtie? What do you think?

**Comment by Leooo** [comment]
Thanks @botandrose got the same issue.
