### ISSUE TITLE
Any way to log the exceptions along with firing notifications?

### ISSUE THREAD

**Issue by matstc** [smartinez87/exception_notification#222]
I am using exception_notification with the email notifier. I receive an email on error but the logs do not mention the exception at all. This seems wrong.

Is there a way to configure exception_notification to always at least log the exceptions?

Or should we create a LogNotifier that can be enabled along the other notifiers?

Thanks.

**Comment by EmilioCristalli** [comment]
@matstc  if you remove exception notification, are exceptions logged correctly?

ExceptionNotification should re-raise the exception after sending the email, so any other rack middlewares should execute as well. `ActionDispatch::DebugExceptions` is probably the middleware responsible for logging errors, so you should see the exception in the logs both with exception_notification or without it

Can you provide more information about the rails version you are using, exception_notification version and configuration?

Thanks!

**Comment by matstc** [comment]
Thanks for responding @EmilioCristalli but the relevant codebase has since been retired. It'd be hard for me to provide more details.

**Comment by EmilioCristalli** [comment]
👍 

Feel free to reopen this issue if you have this problem again with another app

**Comment by synth** [comment]
This is easy to implement yourself with a custom notifier: 

```ruby
Recognize::Application.config.middleware.use ExceptionNotification::Rack,
  logger: ->(exception, options) { Exceptions::Logger.log(exception, options) },
  email: {
    :email_prefix => "[#{Rails.env}] ",
    :exception_recipients => "xyz@example.com",
    :sections => %w(data request session backtrace environment),
    :background_sections => %w(data backtrace),
    :deliver_with => :deliver_later
  }

# then we have a file in app/lib/exceptions.rb
module Exceptions
  class Logger
    def self.log(exception, options)
      Rails.logger.error "Exception: #{exception.class.name} - #{exception.message}"
      Rails.logger.error "options: #{options}"
      Rails.logger.error exception.backtrace.join("\n")
      # ...anything else you need
    end
  def
end
```

NOTE: the reason why you might want a custom notifier is for the cases when you manually call ExceptionNotifier.notify_exception such as in background jobs or places where you catch an exception, but still want to deliver the notification
