### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by jbrodie** [smartinez87/exception_notification#235]
I am following the documentation for the Slack integration but am not having any success on this.  According to the documentation for exception notification:

Slack notifier
This notifier sends notifications to a slack channel using the slack-notifier gem.

Usage
Just add the slack-notifier gem to your Gemfile:

```
gem 'slack-notifier'
```

To configure it, you need to set at least the 'team' and 'token' options, like this:

```
Whatever::Application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :email_prefix => "[Whatever] ",
    :sender_address => %{"notifier" <notifier@example.com>},
    :exception_recipients => %w{exceptions@example.com}
  },
  :slack => {
    :team => "myteam",
    :token => "secret-token",
    :channel => "#exceptions"
  }
```

I have done exactly this but am getting this error on the attempt to deploy to the server.

```
ExceptionNotifier::UndefinedNotifierError: No notifier named 'slack' was found. Please, revise your configuration options. Cause: uninitialized constant ExceptionNotifier::SlackNotifier
```

Has anyone come into this problem, or have ideas on what / why this is happening?

**Comment by ened** [comment]
Meanwhile, people following the README will trip over because their deployment scripts will fail. @smartinez87 please release the updated gem or remove the slack section from the README.

**Comment by marklocklear** [comment]
Hey folks I am getting the 'No notifier named 'slack'' error with Rails 3.2.8 and Ruby 1.9.3. I am following the readme in exception_notification. @ened post above leads me to believe this is not right? How should I be configuring this?

**Comment by monteirobrena** [comment]
I followed all this steps and I didn't receive any errors but I didn't receive notification in Slack. Any idea? Thanks.

**Comment by marklocklear** [comment]
@monteirobrena This was my issue: http://stackoverflow.com/questions/29036234/add-slack-to-exception-notification-gem

**Comment by monteirobrena** [comment]
This is my `config/initializers/exception_notification.rb`

    MyApp::Application.config.middleware.use ExceptionNotification::Rack,
    
    slack: {
      webhook_url:  "https://my_url",
      channel: "#my_channel"
    }

**Comment by monteirobrena** [comment]
@marklocklear thank you, I had your issue, too. I fixed with `4.1.0rc1` but nothing happen in Slack :sob:

**Comment by marklocklear** [comment]
@monteirobrena the initializer you mentioned above I have in config/env/production.rb rather than initializers.

**Comment by monteirobrena** [comment]
@marklocklear now I put in the same that you and no change.

**Comment by rennyallen** [comment]
For guys who's having the same issue, try to add `require 'slack-notifier'` to `config/initializers/exception_notification.rb`
