### ISSUE TITLE
[4.0.1] EmailNotifier may nukes it own instance variables when manually calling notify_exception with user passed :data

### ISSUE THREAD

**Issue by akshetpandey** [smartinez87/exception_notification#239]
Gem version: 4.0.1

While sending a manually triggered exception mail, using:

```
ExceptionNotifier.notify_exception(StandardError.new, data: {options: {}})
```

Basically, `:options` in `:data` replace `@options` in `ExceptionNotifier::EmailNotifier`

In class `ExceptionNotifier::EmailNotifier` line 91, `set_head_variables` is called  which takes all the key and values in `data` passed above and sets them as instance variables.

As a quick fix, I have added the following to my initializer in my rails app so that this doesn't happen, but is certainly not the right fix

```
module ExceptionNotifier
  class << self
    def notify_exception_with_bug_fix(exception, options={})
      options[:data] = {method_params: options[:data]} if options[:data]
      notify_exception_without_bug_fix(exception, options)
    end

    alias_method_chain :notify_exception, :bug_fix
  end
end
```

If any of the following and possibly more keys are passed in `data` it will mess things up, `options, kontroller, exception, env, backtrace, section, data`

**Comment by FLarra** [comment]
It seems that this doesn't make much sense anymore. Feel free to reopen it if you consider so.
