### ISSUE TITLE
Backtrace info in Slack Notifications?

### ISSUE THREAD

**Issue by mikecarroll** [smartinez87/exception_notification#241]
Right now all I see when I get a Slack notifier is the exception explanation and the line in the code it occurred on in the notifier, no backtrace data:

![screen shot 2014-09-30 at 9 03 59 am](https://cloud.githubusercontent.com/assets/217594/4458368/502b667a-48a2-11e4-8e64-5d45c7f6abe1.png)

Is there any way to configure Slack notifications to get the rest of the backtrace data that you would typically get in an exception e-mail (Request, Session, Environment, etc.) in the Slack notification as well?

**Comment by villesundberg** [comment]
I'm working on this right now. I think a good approach could be to save the backtrace into the database and include a URL in the slack notification. Something like `/admin/exceptions/:id`. I'll keep you posted if I manage to make something that would make sense as a PR.

**Comment by elfenars** [comment]
Save the Backtrace to the database?

I think this happens because of the Backtrace cleaner, so a better idea is to just add an optional parameter to wether clean or not the backtrace...

+1

**Comment by jackkinsella** [comment]
I just wanted to chime in and say that our team would LOVE to see this feature in a future release. It's the only thing standing in the way of us running our business entirely through Slack. Rest in peace email.
