### ISSUE TITLE
Sms notification

### ISSUE THREAD

**Issue by sivsushruth** [smartinez87/exception_notification#253]
Is SMS as a delivery option something developers might want ?
If yes, I suggest twilio to do the same.
The SMS can have just the exception without any backtrace.

**Comment by FLarra** [comment]
@sivsushruth In the last version (`4.3.0`) you can notify through sms by using the SNS notifier.

Please consider: https://github.com/smartinez87/exception_notification/blob/master/docs/notifiers/sns.md

Is that useful?

**Comment by FLarra** [comment]
@sivsushruth will close it for now.
I'm happy to reopen & mark as `feature` if you need a different approach.
