### ISSUE TITLE
Send Emails to Sender but not to Receiver

### ISSUE THREAD

**Issue by mariohmol** [smartinez87/exception_notification#254]
Hy , great gem!!

I 'm using but i have a problem, it sends just to the sender email.

  config.middleware.use ExceptionNotification::Rack,
    :email => {
      :email_prefix => "[PP] ",
      :sender_address => 'sender@sender.com',
      :exception_recipients => "receiver@receiver.com"
    
  }

In the sender@sender.com mailbox I have a email written by sender and TO sender.
It do not send the email to receiver@receiver.

Im getting this email from mailserver:

'''

"220-server.sender.com ESMTP Exim 4.82 #2 Mon, 12 Jan 2015 14:13:18 -0200 \r\n"

-> "220-We do not authorize the use of this system to transport unsolicited, \r\n"

-> "220 and/or bulk e-mail.\r\n"

<- "EHLO sender.com\r\n"

-> "250-server.sender.com Hello sender.com [XXX]\r\n"

-> "250-SIZE 52428800\r\n"

-> "250-8BITMIME\r\n"

-> "250-PIPELINING\r\n"

-> "250-AUTH PLAIN LOGIN\r\n"

-> "250-STARTTLS\r\n"

-> "250 HELP\r\n"

<- "STARTTLS\r\n"

-> "220 TLS go ahead\r\n"

<- "EHLO sender.com\r\n"

-> "250-server.sender.com Hello sender.com  [XXXX]\r\n"

-> "250-SIZE 52428800\r\n"

-> "250-8BITMIME\r\n"

-> "250-PIPELINING\r\n"

-> "250-AUTH PLAIN LOGIN\r\n"

-> "250 HELP\r\n"

<- "AUTH LOGIN\r\n"

-> "334 VXNlcm5hbWU6\r\n"

<- "bmFvcmVzcG9uZGFAcHJvc2FzLmNvbS5icg==\r\n"

-> "334 UGFzc3dvcmQ6\r\n"

<- "bmFvcmVzcG9uZGE3Nw==\r\n"

-> "235 Authentication succeeded\r\n"

<- "MAIL FROM:<sender@sender.com>\r\n"

-> "250 OK\r\n"

<- "RCPT TO:<sender@sender.com>\r\n"

-> "250 Accepted\r\n"

<- "DATA\r\n"

-> "354 Enter message, ending with \".\" on a line by itself\r\n"

writing message from String

wrote 8176 bytes

-> "250 OK id=1YAhcF-0003xi-U0\r\n"

<- "QUIT\r\n"

-> "221 server.sender.com closing connection\r\n"

''''

Any ideias? how to set to not send email to itself? to send email just for receiver?

regards,

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by mariohmol** [comment]
I'm using in controller now.. i cant remember how to reproduce it.. thanks for your attetion.. closing
