### ISSUE TITLE
What's the use case for normalize_subject?

### ISSUE THREAD

**Issue by dideler** [smartinez87/exception_notification#255]
I don't understand what `normalize_subject` is used for. The description in the README says

> If enabled, remove numbers from subject so they thread as a single one.

I specifically don't understand what's meant with "so they thread as a single one".

I looked at the code and I see it just substitutes any digits with 'N'. What issue does this prevent?

**Comment by EmilioCristalli** [comment]
this feature was added in https://github.com/smartinez87/exception_notification/pull/39

If i understand correctly, the idea is to help email clients group messages for the same exception together (for those cases when you have different numbers in the subject each time the exception happens for example)

Feel free to reopen the issue if you think this is still not clear enough
