### ISSUE TITLE
email to multiple recipient 

### ISSUE THREAD

**Issue by aditya01933** [smartinez87/exception_notification#262]
Is it possible to send email to multiple recipient with this gem ?
If yes please suggest code.

**Comment by EmilioCristalli** [comment]
@aditya01933 it should be possible to do it specifying an array of recipient addresses in the email notifier configuration, like this:

```ruby
  Rails.application.config.middleware.use ExceptionNotification::Rack,
    email: {
      email_prefix: "[PREFIX] ",
      sender_address: %{"notifier" <notifier@example.com>},
      exception_recipients: %w{recipient1@example.com recipient2@example.com}
    }
```

Can you please try with a configuration like the one above and let us know if you still have issues? Thanks!

**Comment by aditya01933** [comment]
Its working thanks .
