### ISSUE TITLE
NoMethodError: undefined method `default_sections' for ExceptionNotifier::Notifier:Class

### ISSUE THREAD

**Issue by keshavkuruva** [smartinez87/exception_notification#264]
I have upgrade my env from rails 3 to rails 4 and when I run rake. I see below error.

NoMethodError: undefined method `default_sections' for ExceptionNotifier::Notifier:Class
/Users/keshav/Projects/mordor/config/initializers/exception_notification.rb:13:in`<top (required)>'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in`block in load'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in`load'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/engine.rb:608:in`each'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/engine.rb:608:in `block in <class:Engine>'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/initializable.rb:30:in`instance_exec'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/initializable.rb:55:in`block in run_initializers'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/initializable.rb:44:in `each'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/initializable.rb:44:in`tsort_each_child'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/application.rb:215:in`initialize!'
/Users/keshav/.rvm/gems/ruby-2.1.4/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'

Appreciate your help,
Keshav.

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!

**Comment by FLarra** [comment]
Closing this issue based on the previous comment. Feel free to reopen it if it's still an issue.
