### ISSUE TITLE
email not getting triggered, i am migrating from rails 2.3 to rails 3.1

### ISSUE THREAD

**Issue by aksharj** [smartinez87/exception_notification#281]
Hello Admin,

All my other emails are working, but exception email is not working. 

below are the settings in my staging.rb file.

config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true
and following is the code in application.rb

C::Application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :email_prefix => "[#{Rails.env.to_s.upcase} Error] ",
    :sender_address => %{"Exception Notifier " <email_id>},
    :exception_recipients => %w{email_id}
  }
I am not sure why the email is not triggering, nor do i see any error. Any help would be appriciated, Thanks.

**Comment by smartinez87** [comment]
hi @aksharj, can you please specify which version of the gem are you using?

Also, try moving this code
```ruby
C::Application.config.middleware.use ExceptionNotification::Rack,
:email => {
:email_prefix => "[#{Rails.env.to_s.upcase} Error] ",
:sender_address => %{"Exception Notifier " },
:exception_recipients => %w{email_id}
}
```
to the `config/environment.rb` instead of `application.rb`

**Comment by FLarra** [comment]
@aksharj I'll close it for now, but don't hesitate to reopen if you have more information to share so we can help you.
