### ISSUE TITLE
Does not work on Sinatra 1.4.6 on production unless :raise_errors, true

### ISSUE THREAD

**Issue by gffuentes** [smartinez87/exception_notification#286]
On production, Sinatra will rescue exceptions and send an error code instead. This means it does not get to the exception_notification. The solution i have found is to `set :raise_errors, true` in the app, which skips the exceptions rescue. However, the downside is the error page will now show all the whole stack trace.

I am submitting this less as an issue to be fixed, more as something i hope will help someone in the future who is trying to use on sinatra.

see http://www.sinatrarb.com/configuration.html for more on raise_errors

**Comment by FLarra** [comment]
Thanks @gffuentes for the heads up! I'll close this issue because of inactivity around it. However will keep it in mind in case of similar concerns from now on.
