### ISSUE TITLE
Email notifier returning an undefined_method 'backtrace'

### ISSUE THREAD

**Issue by davidchua** [smartinez87/exception_notification#290]
Exception_Notification (4.1.1)
Ruby 2.2.0
Rails 4.2.1

I've ran the Rails Generator

```
rails g exception_notification:install
```

and in my `config/environments/production.rb` configured:

```
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true
# with my smtp setup correctly (i'm about to send and receive email via Rails)
```

When I force a 404 error, I do not receive a email notification as expected. As I'm using mandrill, I'm also not seeing any outgoing e-mail being sent.

When I do a manual notification like:

```
> ExceptionNotifier.notify_exception(ActiveRecord::RecordNotFound)
```

I get an error:

```
#background_exception_notification: processed outbound mail in 2.8ms
An error occurred when sending a notification using 'email' notifier. NoMethodError: undefined method `backtrace' for StandardError:Class
/webapps/tilextile/shared/bundle/ruby/2.2.0/gems/exception_notification-4.1.1/lib/exception_notifier/email_notifier.rb:46:in `background_exception_notification'

```

**Comment by niksfirefly** [comment]
exception_notification not working
same error

Exception_Notification (4.1.1)
Ruby 2.2.3
Rails 4.2.5

**Comment by FLarra** [comment]
It's been a long period of inactivity here. I'm closing it now, feel free to reopen or create a new issue if this is still a problem
