### ISSUE TITLE
Slack notification won't work

### ISSUE THREAD

**Issue by poc7667** [smartinez87/exception_notification#291]
Slack notification won't work

- exception_notification (4.1.1)
- slack-notifier (1.2.1)

# run this function in Rails console to test notification

>
      def a1
        begin
          1/0
        rescue Exception => e
            e=Exception.new
            ExceptionNotifier.notify_exception(e,:env => "development", :data => {:message => e})    
        end
      end

# Exception messages

      W, [2015-10-22T14:54:16.851040 #53346]  WARN -- : An error occurred when sending a notification using 'slack' notifier. NoMethodError: undefined method `first' for nil:NilClass
      /Users/sample1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/exception_notification-4.1.1/lib/exception_notifier/slack_notifier.rb:20:in `call'
      /Users/sample1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:94:in `fire_notification'
      /Users/sample1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:39:in `block in notify_exception'
      /Users/sample1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:38:in `each'
      /Users/sample1/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/exception_notification-4.1.1/lib/exception_notifier.rb:38:in `notify_exception'

# initializers

    Rails.application.config.middleware.use ExceptionNotification::Rack,
    :slack => {
      :webhook_url => "https://hooks.slack.com/services/Txxx",
      :channel => "#exceptions",
      :additional_parameters => {
        :icon_url => "http://image.jpg",
        :mrkdwn => true
      }
    }

**Comment by rodrigopdl** [comment]
This problem has been fixed as of version 4.1.2. Upgrading exception-notification to a newer version should be enough.

**Comment by san650** [comment]
Thanks @rodrigopdl for checking! Closing this issue.

@poc7667 please reopen the issue if you still face any problem.
