### ISSUE TITLE
i receive an error when i send mail

### ISSUE THREAD

**Issue by Yohansun** [smartinez87/exception_notification#293]
An error occurred when sending a notification using 'email' notifier. EOFError: end of file reached
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in`read_nonblock'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:134:in`readuntil'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:945:in`recv_response'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:931:in `block in getok'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:955:in`critical'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:929:in `getok'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:923:in`quit'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:616:in `do_finish'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:523:in`ensure in start'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:523:in `start'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in`deliver!'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in`block in deliver'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.1.rc4/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1.rc4/lib/active_support/notifications.rb:164:in`block in instrument'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1.rc4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1.rc4/lib/active_support/notifications.rb:164:in`instrument'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.1.rc4/lib/action_mailer/base.rb:541:in `deliver_mail'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in`deliver'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.1.rc4/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/bundler/gems/exception_notification-4eda1a4875aa/lib/exception_notifier/email_notifier.rb:143:in`call'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/bundler/gems/exception_notification-4eda1a4875aa/lib/exception_notifier.rb:94:in `fire_notification'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/bundler/gems/exception_notification-4eda1a4875aa/lib/exception_notifier.rb:39:in`block in notify_exception'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/bundler/gems/exception_notification-4eda1a4875aa/lib/exception_notifier.rb:38:in `each'
/superdata/rails/owhat/shared/bundle/ruby/2.2.0/bundler/gems/exception_notification-4eda1a4875aa/lib/exception_notifier.rb:38:in`notify_exception'

my production.rb is this 

Rails.application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :email_prefix         => "Owhat-[#{Rails.env}]",
    :sender_address       => %{"noreply" noreply@owhat.cn},
    :exception_recipients => Rails.env.production? ? %w{prd-alert@owhat.cn} : %w{alert@owhat.cn},
    :delivery_method => :smtp,
    :smtp_settings => {
      :port           => 25,
      :address        => 'smtp.exmail.qq.com',
      :user_name      => ''XXXXXX",
      :password       => 'XXXXX',
      :domain         => 'owhat.cn',
      :authentication => :plain,
    }
  }

**Comment by Yohansun** [comment]
im ok
add config.action_mailer.perform_deliveries = true

**Comment by Yohansun** [comment]
is this one config.action_mailer.raise_delivery_errors = false

**Comment by smartinez87** [comment]
@Yohansun can this issue be closed?
