### ISSUE TITLE
Missing require statement

### ISSUE THREAD

**Issue by betesh** [smartinez87/exception_notification#294]
https://github.com/smartinez87/exception_notification/blob/v4.1.1/lib/exception_notifier/views/exception_notifier/_request.html.erb (as well as the corresponding .text.rb file) use `Time.current`.  `Time.current` is defined in ActiveSupport, creating a dependency on a file that has not necessarily been required.

`require "active_support/core_ext/time/calculations"` should be added to the top of each of these files.

**Comment by betesh** [comment]
Another missing require statement: request.filtered_env is defined in `action_dispatch/http/request`, so that should be require'd in `lib/exception_notifier/views/exception_notifier/_environment.*.erb` and in `lib/exception_notifier/webhook_notifier.rb`

**Comment by EmilioCristalli** [comment]
I think the `Time.current ` issue has been fixed here https://github.com/smartinez87/exception_notification/commit/9bd8ad3a98d6f6b094e5c3c032c04cc1d610b31c

And also both WebhookNotifier and EmailNotifier are doing `require 'action_dispatch'`  now, so i think the `filtered_env ` issue should be fixed as well

Please reopen if this is still a problem!
