### ISSUE TITLE
Releasing anytime soon?

### ISSUE THREAD

**Issue by elfenars** [smartinez87/exception_notification#297]
@smartinez87  how often does this gem get releases?

I'm working with the fork of the fix I made (#283), but there's a lot of others things that have been getting merged and would like to get them also without having to update my fork manually each time I want them. At least in the case of the PR I contributed, it has been almost 4 months.

**Comment by smartinez87** [comment]
@elfenars released a new version just now: https://rubygems.org/gems/exception_notification/versions/4.1.2
