### ISSUE TITLE
How to run with ActionController::Metal ? 

### ISSUE THREAD

**Issue by ericraio** [smartinez87/exception_notification#300]
Since changing my application to use ActionController::Metal, I have stopped receive my notifications and I don't get any exceptions.

Does anyone know what modules are required and I can update the wiki.

**Comment by EmilioCristalli** [comment]
hi @ericraio! do you mind posting the code to reproduce the problem here?

Do you see anything in the logs? When a notifier fails, I think the gem logs something like `An error occurred when sending a notification using ...`
