### ISSUE TITLE
Not compatible with rails 5 

### ISSUE THREAD

**Issue by bigcurl** [smartinez87/exception_notification#304]
Upgrading to the rails 5 beta gave me the following error:

> Bundler could not find compatible versions for gem "actionmailer":
> In Gemfile:

>      exception_notification was resolved to 4.1.2, which depends on
>           actionmailer (~> 4.0)
>  
>     rails (= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
>       actionmailer (= 5.0.0.beta1)

**Comment by smartinez87** [comment]
@bigcurl we'll release a new version of the gem with Rails 5 support once it gets out, most likely next week.

**Comment by dguettler** [comment]
Any update on this?

**Comment by san650** [comment]
There's a WIP PR #306 The idea is to try to release it next week.

**Comment by smartinez87** [comment]
closing, in favor of #306 that was just merged
