### ISSUE TITLE
Rails app server fails to start when using exception_notification as an Engine

### ISSUE THREAD

**Issue by spdawson** [smartinez87/exception_notification#310]
Following the instructions in the README, I ran the generator
```
bundle exec rails g exception_notification:install
```
to generate the `config/initializers/exception_notification.rb` initializer.

However, my Rails app server then fails to start:
```
/whatever/exception_notification-4.1.4/lib/exception_notification/rails.rb:3:in `<class:Engine>': uninitialized constant ExceptionNotification::Engine::ExceptionNotifier (NameError)
```

Modifying the initializer to have the following set of `require`s appears to solve the problem:
```
require 'exception_notifier'
require 'exception_notification/rack'
require 'exception_notification/rails'
require 'exception_notification'
```
Only `exception_notification/rails` is `require`d in the default-generated initializer.

**Comment by san650** [comment]
@spdawson I couldn't reproduce this error. I created a rails app from scratch and installed the gem as you said.

I'm using
```
Rails 4.2.5
Ruby 2.2.3
exception_notification (4.1.4)
```

Can you provide more information on how to reproduce the error? Or better yet, can you upload the app that's failing?

**Comment by spdawson** [comment]
You are quite right --- this was caused by my `Gemfile` including `exception_notification` only in the `:production` group. Sorry for the noise.

**Comment by bogdanRada** [comment]
@spdawson, thank you very much for your workaround, that helped me a lot.  
Had quite the same issue with Rails 4. I tried adding in the initializer this line and had setup the email notifier, but the rack middleware was not being called at all. But after i changed the require statement and added the missing requirements, everything worked :D 
```
 require 'exception_notification'  
```

**Comment by rennyallen** [comment]
Change `require`s doesn't work for me.
For people who is having the same issue, try using the git repo version:
In your Gemfile:
`gem 'exception_notification', git: 'https://github.com/smartinez87/exception_notification.git'`
