### ISSUE TITLE
Website fails to load on https

### ISSUE THREAD

**Issue by san650** [smartinez87/exception_notification#311]
Accessing https://smartinez87.github.io/exception_notification/ fails to load the page due to a Mixing Content error in Chrome 47 (and possible other versions).

<img width="625" alt="screen shot 2016-01-08 at 5 31 00 pm" src="https://cloud.githubusercontent.com/assets/1234607/12208806/dc43b08c-b62d-11e5-8682-5d394fc7bb01.png">

**Comment by ktdreyer** [comment]
Good catch!

Looks like you can change "http" to "https" in your minified documentup javascript.

**Comment by san650** [comment]
Fixed.
