### ISSUE TITLE
EmailNotifier with default configuration broken in Rails 4.0

### ISSUE THREAD

**Issue by san650** [smartinez87/exception_notification#315]
By default EmailNotifier tries to use `ActionMailer::MessageDelivery#deliver_now` method which is not supported.

See https://travis-ci.org/smartinez87/exception_notification/jobs/77609254

<img width="1022" alt="screen shot 2016-01-13 at 8 31 31 pm" src="https://cloud.githubusercontent.com/assets/1234607/12311282/f069bd3a-ba34-11e5-9567-bac44822a441.png">

Tests are not failing because of #314

**Comment by bgracie** [comment]
Hi @smartinez87, @san650.  Any chance you could make a release including this fix?   Looking to upgrade my app to Rails 4.0.  Thanks!
