### ISSUE TITLE
Notified twice with Turbolinks ?

### ISSUE THREAD

**Issue by anthony-robin** [smartinez87/exception_notification#333]
After setting up this gem with the **Slack** notifier, I have discovered I was receiving a notification twice after an exception was raised when clicking a link handled by **Turbolinks**. (I am not sure if it is a real issue or a wrong configuration by me, or even if Turbolinks is involved in that).

**My project details**:
- Rails 4.2.6
- Turbolinks 2.5.3
- Exception Notification 4.1.4
- Slack Notifier 1.5.1

**Comment by Apokly** [comment]
Same problem with Rails 5.0 and slack notifier. Turbolinks is also enabled.

**Comment by roccoblues** [comment]
Pretty sure you have both lines in your production.rb:

`require 'exception_notification/rails'`
and
`config.middleware.use ExceptionNotification::Rack`

At least that was my problem. Remove the first one and everything will work.

**Comment by Apokly** [comment]
It was also my case. Thank you !
