### ISSUE TITLE
Prevent very large Emails

### ISSUE THREAD

**Issue by MartinKoerner** [smartinez87/exception_notification#334]
We use exception_notification with email notifier in a project, were we have some large POST requests with big parameter sets with geo coordinates. The whole request is about 4 MB large.
If now a exception occurs, these 4 MB are shown multiple times in the email (as part of `@request.filtered_parameters`, `@request.filtered_env` and maybe `@exception.message`).

The resulting Email is 17 MB big, which prevents most email clients (like Thunderbird or Apple Mail) to show them correctly. In our cases they hung or crashed. 

I would suggest to implement a string limit to `inspect_object` and call this method for every String in the view. The resulting output then could be like

    ...
    Parameters: Some very long string which doesn't stop anyw...[FILTERED]...
    ...

I'm ready to implement a pull request but wanted to discuss first, if this solution is appreciated.

**Comment by akshaymohite** [comment]
I vote 👍 for the change.

**Comment by Nada1996** [comment]
@MartinKoerner Can you please give us more details about how to recreate the issue ?what was the app you were using?
and is it possible if you can give us steps to help solve the issue .We're working on it and we'll glad if you can give us your suggestions 
Thank you in advance

**Comment by MartinKoerner** [comment]
@Nada1996 We have an application using Google maps to edit routes and have to save every step. So our Javascript made an AJAX POST call with lat/long coordinates for every step, which could get very large...

My idea was to adapt the `inspect_object` method of the email notifier to shrink every outputted string and use the method on every string in the template. Unfortunately I didn't yet have the time to create the pull request.

I saw, that your Pull request #350  solves the problem on a more global scale, so if that gets merged, it will also solve my problem

**Comment by smartinez87** [comment]
closing because #365 got merged
