### ISSUE TITLE
Emails failing after migrating upgrading from 4.1.1 into 4.1.4

### ISSUE THREAD

**Issue by krzcho** [smartinez87/exception_notification#338]
Any idea? Configuration is exactly the same; works in 4.1.1 but it is totally deaf in 4.1.4 (no entries in log, no mails); any idea?

```
TnE::Application.configure do
  config.admin_email = %{krzysztof.chodak@...}
  config.app_email = %{...@...}
  config.middleware.use ExceptionNotification::Rack, :email => {
    :email_prefix => "[Quick] ",
    :sender_address => config.app_email,
    :exception_recipients => [config.admin_email]
  } if ENV['COMPUTERNAME']!="RWAMWCOE31488"
end
```

**Comment by sidviswanathan** [comment]
I rolled back to 4.1.1 and I'm still not able to get things working again. What happened, this gem was so reliable?

**Comment by duleorlovic** [comment]
You need an option `deliver_with: :deliver`
look at this #339

**Comment by ayushlodhi11** [comment]
This issue should get closed now.
