### ISSUE TITLE
Add Mattermost integration

### ISSUE THREAD

**Issue by Aschen** [smartinez87/exception_notification#341]
Hi,

I have developed a custom notifier for Mattermost integration (with incoming webhooks).
Are you guys interested to add it to your project ?

Here some screenshot :
![bot](https://cloud.githubusercontent.com/assets/4447392/16084920/bc84b6d2-331a-11e6-93a4-e2ec517f93d1.png)

**Comment by smartinez87** [comment]
looks nice! you're very welcome to submit a PR 👍

**Comment by Aschen** [comment]
#342 Done
