### ISSUE TITLE
Can I use notifications when errors occur in rake tasks?

### ISSUE THREAD

**Issue by nazarok** [smartinez87/exception_notification#355]

**Comment by smartinez87** [comment]
hi @nazarok, yes you can manually notify.
Take a look at [this part of the readme](https://github.com/smartinez87/exception_notification#background-notifications) for an example

**Comment by smartinez87** [comment]
please re-open if you face any trouble

**Comment by nazarok** [comment]
if I have 100+ rake tasks can I use notifications for errors in one place?
