### ISSUE TITLE
Long backtrace is not formatted

### ISSUE THREAD

**Issue by ivanovaleksey** [smartinez87/exception_notification#362]
Hi. 
I have looked for the same issue but haven't found.

I have noticed that long backtrace is not formatted by Slack.
I think it happens because attachment field with whole backtrace exceed some Slack limits (I am not sure whether it is really so, but it seems like it is).

![image](https://cloud.githubusercontent.com/assets/11523473/17969154/5f6799d2-6ad9-11e6-8faf-187e8fc1e596.png)

As you can see ``` starts but doesn't close.

I found [here](https://github.com/smartinez87/exception_notification/blob/master/lib/exception_notifier/slack_notifier.rb#L44) that one can pass `backtrace_lines` as middleware option to reduce backtrace size.
In my case `backtrace_lines: 15` is maximum size that allows backtrace to be formatted.

![image](https://cloud.githubusercontent.com/assets/11523473/17969272/fbbdce82-6ad9-11e6-9167-a4060444e9ca.png)

So the question is: can we overcome Slack field size limits?
If we can't see the whole backtrace can we remove ``` [here](https://github.com/smartinez87/exception_notification/blob/master/lib/exception_notifier/slack_notifier.rb#L44) (in else case)? 
Because I think no Rails backtrace could be small enough to fit 15 Slack lines.

Thanks.

**Comment by spejamchr** [comment]
This is happening to me, too. According to [this tweet](https://twitter.com/SlackHQ/status/754026699621330944) from Slack in Jul 2016, they set a limit at 8000 characters. However, in my experience the limit is 2000 characters.

**Comment by ivanovaleksey** [comment]
@smartinez87 could you please check it out? In my current project I use `backtrace_lines` and it does help. I could close the issue or there is anything to be done here?
