### ISSUE TITLE
Merge exception_notification-rake gem

### ISSUE THREAD

**Issue by moubry** [smartinez87/exception_notification#369]
I've been using the extension gem https://github.com/nikhaldi/exception_notification-rake, which has worked great for me so far. However, it hasn't been updated in a while, and doesn't work with Rails 5.

So, I was wondering, does it make sense to have this functionality in exception_notification itself?

I know there is [documentation for background notifications](https://github.com/smartinez87/exception_notification#background-notifications), but it seems like it would be generally useful to automatically get notified of exceptions in Rake tasks too.

What do you think?

**Comment by duleorlovic** [comment]
You can simply override rake task to call manual exception [source](# http://stackoverflow.com/questions/7161374/rails-exception-notifier-in-rake-tasks)

~~~
require 'rake/task'
module Rake
  class Task
    alias orig_execute execute
    def execute(args = nil)
      orig_execute(args)
    rescue Exception => exception
      ExceptionNotifier.notify_exception(exception)
    end
  end
end
~~~
This works fine for me.

**Comment by FLarra** [comment]
Closing this now because of inactivity. If @duleorlovic solution is not enough @moubry please PR this feature.

**Comment by TylerRick** [comment]
I really like this idea. I've been using (and contributing to) https://github.com/nikhaldi/exception_notification-rake, too, but it just seems, as [moubry](https://github.com/moubry) so perfectly put it...

> ... like it would be generally useful to automatically get notified of exceptions in Rake tasks too.

Wouldn't most `exception_notification` users like to automatically be notified of errors occurring in their application _generally_ — including from background jobs? Airblade does that, for example. Like it says in their [railtie.rb](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/railtie.rb)):

> It makes Airbrake Ruby work with Rails and report errors occurring in the application automatically.

Why not do the same thing for us `exception_notification` users, too, without the need for extra gems? The name of this project, after all, isn't `exception_notification_middleware` or `exception_notification_from_web_requests`, but just `exception_notification` generally. :-)

I'll take a quick look to see if I could put together a quick PR...

Should this be enabled by default? Should there be an option to opt out? Looking at Airblade, I see they _used_ to have a  `rescue_rake_exceptions` option, but it was removed in v 5, so I'd be inclined to just make it always enabled...

I figure this will only handle _unhandled_ exceptions from rake/runner. If you don't want this default handler from `exception_notification` to handle the error, you can always just rescue and handle the exceptions some other way!

**Comment by TylerRick** [comment]
All right, I've put together a PR, #536, for this. Please let me know if you think we could get that merged.
