### ISSUE TITLE
Not able to control whether controller/action names are included in email subject

### ISSUE THREAD

**Issue by ImMatureTony** [smartinez87/exception_notification#373]
I'd like to be able to strip these since the on-call system we use generates a distinct incident per-unique subject line, and right now a single root issue too often generates many incidents (despite the "normalize_subject" option helping cut down on that a bit).

**Comment by ImMatureTony** [comment]
I've put in a pull request that adds the ability to control this:
https://github.com/smartinez87/exception_notification/pull/374/files

**Comment by FLarra** [comment]
Closing this issue since the suggested changes have already been merged.
