### ISSUE TITLE
Unable to connect to Enterprise HipChat Server

### ISSUE THREAD

**Issue by seanhuber** [smartinez87/exception_notification#382]
Currently there isn't a way to set the `:server_url` for an Enterprise HipChat Server (like there is for the HipChat API Wrapper gem: [HipChat Wrapper README - Custom Server URL](https://github.com/hipchat/hipchat-rb#custom-server-url)).

I've submitted a pull request [(381)](https://github.com/smartinez87/exception_notification/pull/381) that fixes this issue.

**Comment by seanhuber** [comment]
Is there anyone available to review this proposal?

**Comment by smartinez87** [comment]
closing since #381 got merged
