### ISSUE TITLE
Invalid notifier 'error_grouping'

### ISSUE THREAD

**Issue by krsyoung** [smartinez87/exception_notification#383]
Curious if anybody else is making used of the `error_grouping` option?  I am getting the following error:

```
.../2.4.0/gems/exception_notification-4.2.1/lib/exception_notifier.rb:59:in `register_exception_notifier': Invalid notifier 'error_grouping' defined as true (ArgumentError)
	from .../2.4.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:27:in `block in initialize'
	from .../2.4.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:26:in `each'
```

This is based on the following configuration found in `config/environments/production.rb`:

```
  # Exception notification
  config.middleware.use ExceptionNotification::Rack,
    ignore_exceptions: ['ActionView::MissingTemplate'] + ExceptionNotifier.ignored_exceptions,
    error_grouping: true,
    email: {
      email_prefix: "[OOPS] ",
      sender_address: %{"exceptions" <exceptions@example.com>},
      exception_recipients: %w{info@example.com}
    }
```

If I remove the `error_grouping: true` line everything works as expected.

Versions are:
* Rails 5.0.2
* exception_notification 4.2.1 
* ruby 2.4.0p0

**Comment by Martin91** [comment]
Hi @krsyoung , the error grouping is developed by me and I havd used it for a month. Are you using this gem from github because the error grouping is only available from master branch in github, maybe it will be released soon.

**Comment by krsyoung** [comment]
Duh, ok thanks @Martin91!  I was using the gem from rubygems.  I'll mark this as closed and follow-up if I have any issues from master. 👍 awesome work on the feature my friend!

**Comment by bhushangahire** [comment]
Can we release Error Grouping to rubygems?
