### ISSUE TITLE
ignore_if seems to be ignored

### ISSUE THREAD

**Issue by giamma13** [smartinez87/exception_notification#385]
Hi there

I am using :ignore_if, but I do not see my code being called
* :ignore_if => ->(env, exception) { Global.ex_notification_ignore_if(env, exception) },

I have a method Global.ex_notification_ignore_if(env, exception) that take the exception and figures out weather to return true or false

my method has also few calls to Rails.logger that I do not see.

Any idea on why ?

**Comment by bhushangahire** [comment]
+1

**Comment by EmilioCristalli** [comment]
@giamma13 ignore_if is not executed, but the notifier is still triggered? Or it is not notifying either?

What version of the gem are you using? And what version of Rails? 

Anything in the logs? If there's an exception in the ignore if code it should log something

Can you share your configuration?

**Comment by rvfx** [comment]
I have the same issue with this option:

`ignore_if: ->(env, exception) { exception.message.include?('504 Gateway Time-out')}`

I still get emails with this content:

```
A JSON::ParserError occurred in background at 2024-02-08 15:48:28 UTC :

 809: unexpected token at '<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
```

I tried all kind of versions of this, but `ignore_if` seems to be ignored completely. `ignore_crawlers` work though.
