### ISSUE TITLE
Is error grouping functionality completed? Can you push it to Rubygems? 

### ISSUE THREAD

**Issue by bhushangahire** [smartinez87/exception_notification#386]
I think error grouping will solve my purpose of grouping similar emails and stop sending them multiple time within given timeframe.

**Comment by Martin91** [comment]
@bhushangahire Have you tried using it in your application? I think @smartinez87 is waiting for seeing if the new feature will break something. We have used this new feature in our production environment more than 2 applications, and it worked very well for use.

**Comment by matteofuzz** [comment]
On Rails all ok, but on a pure Grape rest service we have a very hard to find bug with this exception only in production environment:
````
16:02:06 sss.1  | [3] pry(#<Grape::Endpoint>)> continue
16:02:06 sss.1  | 127.0.0.1 - - [08/May/2017:16:02:06 +0200] "GET /api/v0/nnn/11111111/call.json/?some_param=some_value HTTP/1.1" 200 1111 22.2222
16:02:06 sss.1  | NoMethodError - undefined method `cache' for Rails:Module:
16:02:06 sss.1  |    ... bundler/gems/exception_notification-xxxxxxxxx/lib/exception_notification/rack.rb:16:in `initialize'
````
(Just a warning).

**Comment by Martin91** [comment]
@matteofuzz thanks for the report. I will try to reproduce and fix this problem.

**Comment by Martin91** [comment]
@matteofuzz feel so sorry that I am too busy to debug your report. Could you provide more information so I can try to fix this.
* What means `a pure Grape`, is it a app with Grape only? and not a Rails application?

**Comment by Martin91** [comment]
@matteofuzz in `exception_notification/lib/exception_notification/rack.rb:16`, there are below lines:
```ruby
if options.key?(:error_grouping_cache)
  ExceptionNotifier.error_grouping_cache = options.delete(:error_grouping_cache)
elsif defined?(Rails)
  ExceptionNotifier.error_grouping_cache = Rails.cache
end
```
It means, if you are not in a Rails application, a `:error_grouping_cache` option is expected. It represents an instance of your cache class. More information, see [README: Error Grouping](https://github.com/smartinez87/exception_notification#error-grouping)

**Comment by Martin91** [comment]
@matteofuzz coulu you confirmed the above solution.

**Comment by Martin91** [comment]
@bhushangahire FYI, @smartinez87 had released v4.2.2. https://rubygems.org/gems/exception_notification/versions/4.2.2

**Comment by bhushangahire** [comment]
Wow nice. Will test this today.

**Comment by FLarra** [comment]
Closing this issue now. Seems we are good here.
