### ISSUE TITLE
Slack ignore_data_if filter to reduce messages

### ISSUE THREAD

**Issue by tuxtux59** [smartinez87/exception_notification#387]
Hi,

We are currently facing a recurrent API error that send to much messages on our exceptions channel.
I found that `ignore_data_if` key code can filter errors.

Our recurrent error post "An exception occurred while doing: `POST /some/url/`"

Is it possible to avoid the sendings for this POST action to our Slack using ìgnore_data_if`?

Thanks

**Comment by EmilioCristalli** [comment]
@tuxtux59 you can use one of the options to ignore exceptions mentioned here https://github.com/smartinez87/exception_notification/blob/master/README.md#ignore-exceptions

The ignore_if is the most flexible one, should let you specify a proc with conditions to filter certain exceptions and not notify them.

You can also use the error grouping feature to stop it from notifying every single time it happens, and only do it if it happens x times in a period of time

Let us know if you need help setting it up or if it doesn't work for you
