### ISSUE TITLE
Option to no longer notify about InvalidAuthenticityToken errors

### ISSUE THREAD

**Issue by mb21** [smartinez87/exception_notification#389]
Could [this pull from the old rails repo](https://github.com/rails/exception_notification/pull/16) be considered? Thanks.

**Comment by smartinez87** [comment]
Hi @mb21, what are you trying to accomplish with this?
If you intend to ignore the `InvalidAuthenticityToken`, why not use the `ignore_exception` option? Check [this section](https://github.com/smartinez87/exception_notification#ignore-exceptions) out

**Comment by mb21** [comment]
Thanks! I must have read up on old API-docs where that option didn't exist yet...
