### ISSUE TITLE
Exception Notification mail not sent from production

### ISSUE THREAD

**Issue by nk-mandilwar** [smartinez87/exception_notification#390]
ExceptionNotifier is not sending mail from production, though I can see mail being sent in the log file, but it is not reaching to me. When I tried to send mail from console, inside server, using ExceptionNotifier, I am receiving mail.
ExceptionNotifier is sending email in 30000 ms from the app while taking 700 ms from the console in server computer. Is this the reason?
Please do help.

**Comment by nk-mandilwar** [comment]
@smartinez87 Can you help me with this?

**Comment by stevenup** [comment]
I came across the same problem. I followed the instructions and placed the code below in both environments `development.rb` and `production.rb`, but I could only receive emails from local development env. When I deploy code on production env, I received nothing in spite of errors occurred.

> Rails.application.config.middleware.use ExceptionNotification::Rack,
                                          :email => {
                                            :deliver_with => :deliver, # Rails >= 4.2.1 do not need this option since it defaults to :deliver_now
                                            :email_prefix => "[FaceWaver Error] ",
                                            :sender_address => %{"notifier" <notifier@tttt.com>}, # Not my real email address.
                                            :exception_recipients => %w{steven.tang@tttt.cn} # Not my real email address.
                                          }
  config.action_mailer.delivery_method = :sendmail
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true

**Comment by stevenup** [comment]
@nk-mandilwar Did you solve the problem. I found a line says `/usr/sbin/sendmail not found`, so i tried running `sudo apt-get install sendmail` and then It worked. Notification emails now come when errors occur.

**Comment by nk-mandilwar** [comment]
@stevenup No. I couldn't solve it yet. Did you find the solution?

**Comment by Gomathi-N** [comment]
@nk-mandilwar Have you found out any solution?

**Comment by voordev** [comment]
This problem stil persist in 2019, having a production application with exceptionmailer not working.
Having both the same code blocks for environment development and production.
It even works in 'staging' environment.

Conclusion,. there must be a conflicting parameter inside the production environment preventing the mails to be send out.

What is causing this issue anyone found a solution?

**Comment by chetanbothra** [comment]
voordev : What is the web server you are using in dev and prod ? i am getting the same thing when i use puma as my web server but works fine when I use thin

**Comment by EmilioCristalli** [comment]
do you have any other notifiers configured? are they being triggered? (just to determine if the problem with the integration with exception notification or with the email notifier itself)

Can you provide your ExceptionNotification and mailer configuration? (obviously without sensitive data)

Are you using Rails? which version?
And which version of the gem are you using?

Any errors in the logs?

**Comment by tnvr000** [comment]
development:
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true
config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = { address: 'localhost', port: 1025 }
config.middleware.use ExceptionNotification::Rack,
  :email => {
    :deliver_with => :deliver,
    :email_prefix => "[PREFIX] ",
    :sender_address => %{"notifier" <notifier@example.com>},
    :exception_recipients => %w{ notifier@example.com }
  }

staging:
config.action_mailer.raise_delivery_errors = true
config.action_mailer.perform_deliveries = true
config.action_mailer.default_url_options = { :host => "<host>" }
ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.perform_deliveries = true
ActionMailer::Base.raise_delivery_errors = true
config.action_mailer.smtp_settings = {
  :address              => "smtp.mandrillapp.com",
  :port                 => 587,
  :domain               => '[FILTERED]',
  :user_name            => '[FILTERED]',
  :password             => '[FILTERED]',
  :authentication       => 'plain',
  :enable_starttls_auto => true
}
config.middleware.use ExceptionNotification::Rack,
  :email => {
    :deliver_with => :deliver,
    :email_prefix => "[PREFIX] ",
    :sender_address => %{"Name" <notifier@example.com>},
    :exception_recipients => %w{receiver@example.com}
  }

**Comment by tnvr000** [comment]
Above is requested information.
