### ISSUE TITLE
Exception not printed

### ISSUE THREAD

**Issue by thebravoman** [smartinez87/exception_notification#391]
In the email I receive I get only

```
A SomeException occurred in models#destroy:

  An error occurred calling the Some models service
  app/models/models.rb:59:in `cancel'
```

How could I print the message that is in SomeException? In is not included anywhere.

**Comment by Martin91** [comment]
Too less information, could you provide more information? Such as some lines of your codes.

**Comment by thebravoman** [comment]
Unfortunately not. The code is already changed. But the problem was that the message in the  exception occurring in the models.rb:59 was not printed. There is a message in this exception but the message was not printed.

**Comment by jaleszek** [comment]
Hey,
Same problem here.
I can reproduce both - locally and on Heroku.

Some standard Rails/Rack configuration:

```
  config.middleware.use ExceptionNotification::Rack,
    email: {
      email_prefix: "[...] ",
      sender_address: %{"notifier" <...>},
      exception_recipients: %w{..}
    }
```

In email exception I don't get backtrace section just laconic information at the top:

```
An ActionView::Template::Error occurred in somecontroller#index:
undefined method `series_name' for nil:NilClass
```

**Comment by jaleszek** [comment]
Ok I found solution by defining custom section and using

```
<%=pp @exception.backtrace.join("\n") %>
```
