### ISSUE TITLE
uninitialized constant ExceptionNotification in production

### ISSUE THREAD

**Issue by dsvoba** [smartinez87/exception_notification#395]
In development environment (rails 4.2.4) everything works fine, but I get uninitialized constant error in production:

`ERROR -- : uninitialized constant ExceptionNotification (NameError)
/xxx/config/environments/production.rb:90:in`

and the production.rb looks like this:

```
Rails.application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    ...
  }
```

Any suggestions?

**Comment by Martin91** [comment]
Check your `Gemfile` to ensure this gem is installed under production group, too. I guess you have put it under only `development`  group.

**Comment by FLarra** [comment]
@dsvoba I think what @Martin91 told you a long time ago could have been the issue. Feel free to reopen with more information if this keeps happening.
