### ISSUE TITLE
Notification emails broken layout

### ISSUE THREAD

**Issue by aussiDavid** [smartinez87/exception_notification#397]
Please see the attached screenshot from an exception notification sent via email on Gmail.

![screen shot 2017-08-30 at 4 15 09 pm](https://user-images.githubusercontent.com/5856280/29859024-5cb72538-8d9f-11e7-968a-1fea3c1c40b8.png)

**Comment by FLarra** [comment]
@aussiDavid is this still happening? 

Can you please provide more information about how you are using the gem?

**Comment by aussiDavid** [comment]
The issue seems to be resolved. I must have updated to a later version of the gem.
