### ISSUE TITLE
Exception notification emails are sent twice

### ISSUE THREAD

**Issue by marzapower** [smartinez87/exception_notification#399]
I am facing this strange issue where I receive two copies of the exception notification emails at the same time, and two copies of those notifications in the Slack channel too.

I haven't been able to understand where the issue originates, so I am asking you to help me solve this. I am currently using version `4.2.2` of this gem, I have a single initializer file like this:

```ruby
require 'exception_notification/rails'
require 'exception_notification/sidekiq'

if Rails.env.production?

  Rails.application.config.middleware.use ExceptionNotification::Rack,
    ignore_exceptions:        %w[ActionController::InvalidCrossOriginRequest] + ExceptionNotifier.ignored_exceptions,
    ignore_crawlers:          %w[Googlebot bingbot],

    email: {
      email_prefix:           "[Crash Notifier] ",
      sender_address:         %["Crash Notifier" <monitor@domain.com>],
      exception_recipients:   %w[email1@domain.com email2@domain.com],
      sections:               %w[request session backtrace environment]
    },

    slack: {
      webhook_url:            "https://hooks.slack.com/services/custom_channel_webhook",
      channel:                "#bug-me-more",
      additional_parameters: {
        mrkdwn: true
      }
    }

end
```
No other references to `ExceptionNotification` or `ExceptionNotifier` are found throughout the rest of the code.

**Comment by roccoblues** [comment]
I had the same problem. You need to remove the line `require 'exception_notification/rails'`. That also installs the rack middleware leads to the notifications send twice.

**Comment by marzapower** [comment]
@roccoblues you saved my day!
