### ISSUE TITLE
How do I get http user agent in error emails?

### ISSUE THREAD

**Issue by NidhiArien** [smartinez87/exception_notification#400]
Currently when ever a browser request fails, I have set up to be notified for error email notification. While it is incredibly  helpful, I cannot decipher what the browser user agent for the request was: 

HTTP_USER_AGENT      :Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Is there any way I could get more details on the browser name, browser version of the request?

**Comment by EmilioCristalli** [comment]
@NidhiArien if i understand correctly you are getting the UA in the email, but you want to convert that to the specific browser/OS?

I think you can use something like this to do it: https://developers.whatismybrowser.com/useragents/parse/

Let us know if that helps!

**Comment by FLarra** [comment]
Thanks @EmilioCristalli for the reply & @NidhiArien for the original question. I'd close this issue for now, but please reopen it if you feel we need to circle back and find a solution together.
