### ISSUE TITLE
Nothing in notification email body

### ISSUE THREAD

**Issue by ddayporter** [smartinez87/exception_notification#401]
On Rails 5.1.1 and the mailjet api, we're getting error notifications with blank email bodies (truncated verbose subject line is working).

In production.rb: 
```
Rails.application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :email_prefix => "[ERROR] ",
    :sender_address => %{"Data Center Notifier" <validemail@org.org>},
    :exception_recipients => %w{email1@org.org email2@org.org}
  }
```

In application_controller.rb:
```
before_action :prepare_exception_notifier

private
def prepare_exception_notifier
  request.env["exception_notifier.exception_data"] = {
    :current_user => current_user
  }
end
```

Screenshot of email received (with pop-up showing full subject line).
<img width="764" alt="exception_notification_email" src="https://user-images.githubusercontent.com/14064144/31999890-da35799e-b962-11e7-9641-385f4a12cfdc.png">

**Comment by ddayporter** [comment]
I solved this by specifying html as email format. Not really sure why text format wasn't working, but html works, and looks great.

**Comment by EmilioCristalli** [comment]
@ddayporter i couldn't reproduce the issue with `text` format. What version of exception-notification were you using?

Any chance you can provide a sample code to reproduce it?

**Comment by EmilioCristalli** [comment]
Going to close this issue since there has been no response for a long time. With only the
information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
