### ISSUE TITLE
Get notification only for 500 error

### ISSUE THREAD

**Issue by muraree** [smartinez87/exception_notification#403]
Hello
I want to send a slack message only for 500 error(internal server error)
Can I achieve this ?

**Comment by EmilioCristalli** [comment]
@muraree are you using Rails or Sinatra or something else?

I think Rails automatically rescues 404s and shows the 404 template, so the exception shouldn't be handled by Exception Notification.
Also I think Rails only responds with a 500 error for unhandled exceptions, and those are the ones that exception notification catches and notifies, so probably you should be able to do this but I might be missing some special scenarios.

Do you have an example of a non-500 response that you want exception notification not to report?

**Comment by EmilioCristalli** [comment]
Going to close this issue since there has been no response for a long time. With only the
information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
