### ISSUE TITLE
Use in rails 5 results in ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by thebravoman** [smartinez87/exception_notification#412]
Exception_notification version 4.2.2

Worked perfectly well in rails 4.2 Upgrading to rails 5.1 and the following exception happens on login

````
ActionController::InvalidAuthenticityToken
````
This is the code of the ApplicationController
````
class ApplicationController < ActionController::Base
	
	protect_from_forgery prepend: true, with: :exception

  before_action :prepare_exception_notifier
  
	private
	def prepare_exception_notifier
    request.env["exception_notifier.exception_data"] = {
      :current_user => current_user
    }
  end
  
end

````

If I remove the
````
  before_action :prepare_exception_notifier
````
then I am able to login.

**Comment by thebravoman** [comment]
If  in prepare_exception_notifier 'current_user' is never called then no exception occurs.

````
request.env["exception_notifier.exception_data"] = {
      :current_user => User.first
    }
````

**Comment by FLarra** [comment]
@thebravoman could you find the root cause?

In rails 5, `protect_from_forgery` execution order has changed. Since you are using the option
```rb
prepend: true
```
rails will execute the forgery protection as the very first before_action, however if you don't have the current_user setup this will cause a failure. Make sure you have authenticated the user before the `protect_from_forgery` hook is called. I.e: having a ```before_action :authenticate_user!```

**Comment by thebravoman** [comment]
@FLarra I am using devise for authentication.  Order does not solve it

With the following code below the same exception is still occurring 
````
	before_action :authenticate_user!
	protect_from_forgery with: :exception
	before_action :prepare_exception_notifier
````

**Comment by EmilioCristalli** [comment]
@thebravoman i wasn't able to reproduce this using these gem versions:
Rails 5.1.6.1
Devise 4.5.0
exception_notification 4.2.2

An `InvalidAuthenticityToken` exception usually means a problem with the CSRF token, so not sure if this could be related to exception_notification. 

Any chance you can provide the code for a sample app to reproduce the issue?

**Comment by EmilioCristalli** [comment]
Going to close this issue since there has been no response for a long time. With only the
information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
