### ISSUE TITLE
email works, slack does not

### ISSUE THREAD

**Issue by swe9** [smartinez87/exception_notification#414]
ruby 2.4.1, rails 5.1.6, exception-notification 4.2.2, slack-notifier 2.3.2

no slack notification
nothing in the logs related to slack
email has expected content

**Comment by swe9** [comment]
Same configuration worked in Airbrake

**Comment by EmilioCristalli** [comment]
hi @swe9 , i wasn't able to reproduce the issue with the same gem versions.
Can you please confirm if the webhook is correctly configured in Slack?
You can do it by sending a POST request to your webhook url with a body like this: `{"text": "Test"}`

```bash
curl -X POST https://hooks.slack.com/services/XXXXXX/XXXXXX/xXxXxXxX -d '{"text": "Test"}'
```

**Comment by FLarra** [comment]
@swe9 if you have more information to provide please feel free to reopen it and share what you have, so we work on it together.
