### ISSUE TITLE
Testing manual notifications

### ISSUE THREAD

**Issue by Startouf** [smartinez87/exception_notification#415]
Hello,
Do you have some guidelines, or spec helpers to help test ExceptionNotification when manually triggering exceptions ?

For instance I'd like to add specs to this

```
def some_process
  ...
  semi_critical_call_method
end

def semi_critical_call_method
  code_that_may_crash
rescue => e
  ExceptionNotifier.notify_exception(e)
end
```

Mocking a crash : 

```
before { allow(subject).to receive(:semi_critical_call_method).and_raise(SomeException) }

 it 'does not crash' do 
  expect { subject.some_process }.not_to_raise_error 
end

it 'sends a notification through Exception notifier'
  ??
end
```

**Comment by EmilioCristalli** [comment]
what if you do `expect(ExceptionNotifier).to receive(:notify_exception)` ?

there's probably better ways to do it, but i guess this could work, assuming `ExceptionNotifier` works properly it should notify correctly

**Comment by Startouf** [comment]
Yes actually I ended up using exactly something like this

```
expect(::ExceptionNotifier).to(
  receive(:notify_exception).with(
    an_instance_of(::RuntimeError), data: {}
  )
)
```

This works perfectly for services, but then it becomes a little bit trickier with env stuff (cf https://github.com/smartinez87/exception_notification#custom-data-eg-current-user)

```
request.env['exception_notifier.exception_data']
request.env['exception_notifier.current_user']
```

because this somewhat automatically adds data to Exception notifier payload but I'm not really sure how to test this... any idea ? Or should I just test that this request env variable is set when testing errors in my request specs ?

**Comment by EmilioCristalli** [comment]
yeah, i think you can just test that the env key is set correctly, and then assume Exception Notification is working properly and will use it

Or maybe if you want to do more an integration test, you might want to test that the notifier is being triggered (for ex if you have the email notifier you might want to test that an email is being generated and that it contains whatever you are putting in `request.env['exception_notifier.exception_data']`)
