### ISSUE TITLE
How do I notify to Amazon SNS?

### ISSUE THREAD

**Issue by a-suenami** [smartinez87/exception_notification#425]
Hi, there. Thank you for the great gem.

I want to notify all exceptions in our application to Amazon SNS (Simple Notification Service) and then register any subscribers without the deployment of the application.

Do you have the plan to support Amazon SNS notifier? How and when do I use it?

Thnaks.

**Comment by FLarra** [comment]
Hi @a-suenami thanks for reaching out! It's a great feature request, I'll consider it and probably will start working on it in the next days.

**Comment by a-suenami** [comment]
@FLarra Thank you so much!

I'm looking forward to finishing your working and using the new feature.

**Comment by FLarra** [comment]
@a-suenami Sorry for the delay I finally got the chance to finish it. Hope it helps you!

https://github.com/smartinez87/exception_notification/pull/433
