### ISSUE TITLE
Is there a way to silence ActionController::UnknownHttpMethod errors?

### ISSUE THREAD

**Issue by timokleemann** [smartinez87/exception_notification#465]
I sometimes get a dozen or so emails like these:

> An ActionController::UnknownHttpMethod occurred in #:
> 
>  TRACK, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH

I guess this is when bots are hitting my site with HTTP methods that Rails can't handle.

Is there a way to *silence* these messages or is this a Rails or web server (NginX) issue?

### System configuration
**Rails version**:
5.2.2

**Ruby version**:
2.4.0

**Comment by EmilioCristalli** [comment]
@timokleemann i think you can do it with the `ignore_exceptions` option:

```ruby
Rails.application.config.middleware.use ExceptionNotification::Rack,
  ignore_exceptions: ['ActionController::UnknownHttpMethod'] + ExceptionNotifier.ignored_exceptions,
  email:  { ... }
```

**Comment by timokleemann** [comment]
Problem solved. Thank you!

**Comment by WaseekSenju** [comment]
I have same scenario bots sending requests with methods like PURGE etc. where should I put this piece of code in my application?
