### ISSUE TITLE
Ignoring sensitive params from Email

### ISSUE THREAD

**Issue by puneet-khushwani-bits** [smartinez87/exception_notification#472]
### Steps to reproduce

1. Add some params to be ignored as per code below

config/initializers/filter_parameter_logging.rb 
Rails.application.config.filter_parameters += [:password]

2. Notify in case of exception

params = {password: 'testtest'}
se = StandardError.new('Test Error')
ExceptionNotifier.notify_exception(se, data: {params: params})

### Expected behavior

Email body should show password as

* data: {:params=>{:password=> [FILTERED] }}

### Actual behavior

It reveals the password

* data: {:params=>{:password=>"testtest"}}

### System configuration

**Rails version**:
5.2.2.1

**Ruby version**:
ruby-2.5.3

**Comment by EmilioCristalli** [comment]
@puneet-khushwani-bits  i think exception notification will only filter params from the `env`. 
Feels like it should be the user's responsibility to filter out anything from the custom data you add to the notification

thoughts?

**Comment by puneet-khushwani-bits** [comment]
@EmilioCristalli 

We have config.middleware.use ExceptionNotification::Rack  in our application.rb.

We notice that in case of unhandled exceptions from our App, the mail that is being sent to us by ExceptionNotifier handles filtering of sensitive params (respecting config/initializers/filter_parameter_logging.rb). 

We were trying to reuse that feature by calling ExceptionNotifier.notify_exception(se, data: {params: params}). 

Is there any other method we could use ?

Thanks,

**Comment by EmilioCristalli** [comment]
@puneet-khushwani-bits you can try this `ExceptionNotifier.notify_exception(exception, env: request.env)` if you are calling it from a controller. I think if you call it this way it should filter params like when it does for unhandled exceptions 

Let us know if it works

**Comment by puneet-khushwani-bits** [comment]
Thanks for the advice @EmilioCristalli . It worked for us.
