### ISSUE TITLE
Switch to a new slack gem?

### ISSUE THREAD

**Issue by firefart** [smartinez87/exception_notification#489]
It looks like the used `slack-notification` gem is not developed any more and there are some deprecation warnings with ruby 2.7 meaning the gem will most likely stop to function in the near future (https://github.com/stevenosloan/slack-notifier/issues/115).
Would it be possible to switch the current implementation to https://github.com/slack-ruby/slack-ruby-client or another actively maintained project?

**Comment by nicolasferraro** [comment]
Thanks for bringing this to our attention! I think switching to an actively maintained gem makes sense. Let me see what I can do!

**Comment by FireFart** [comment]
Cool thanks! If it helps, here is my custom notification implementation with basic functionality and without fancy content included.
This new gem requires you to create an app on slack (https://api.slack.com/apps), add the `chat:write` oauth permission, add a user and install it into the workspace. Then you need to `/invite` the new bot user to the channel you want to post.
Afterwards you can copy the generated slack token to the app. So it's slightly more complex than the old way and I fear it will not be backwards compatible.

```ruby
# frozen_string_literal: true

module CustomSlack
  class << self
    def client
      return @client if !@client.nil?

      Slack.configure do |config|
        config.token = ENV['SLACK_API_TOKEN']
      end
      @client = Slack::Web::Client.new
      return @client
    end
  end
end
```

```ruby
ExceptionNotifier.add_notifier :custom_slack_notifier, ->(exception, options) { CustomSlack.client.chat_postMessage(channel: '#exceptions', text: "[Applicationname] #{exception.full_message(highlight: false, order: :top)}", as_user: true) }
```
