### ISSUE TITLE
sender_address overwritten by ActionMailer::Base.default_options after 4.4.1

### ISSUE THREAD

**Issue by everton** [smartinez87/exception_notification#493]
### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'exception_notification', '4.4.1'
end

ENV['RAILS_ENV'] ||= 'test'

require 'action_mailer'
require 'minitest/autorun'

ActionMailer::Base.delivery_method = :test
ActionMailer::Base.default_options = {
  from: '"Default E-mail" <default@>'
}

ExceptionNotification.configure do |config|
  config.add_notifier :email, {
    sender_address: '"Bugs!" <bugs@example.com>',
    exception_recipients: ['dev@example.com']
  }
end

class BugTest < Minitest::Test
  def test_custom_notification
    err = Exception.new('Testing notifications')

    ExceptionNotifier.notify_exception(err)

    notified_email = ActionMailer::Base.deliveries.last

    refute_nil notified_email

    assert_equal ['bugs@example.com'], notified_email.from
  end
end
```

### Expected behavior

Until 4.4.0 the `sender_address` config was taken as "from" option overwritten the ActionMailer default "from config.

### Actual behavior

Updating to 4.4.1 the behavior changed and now ActionMailer default "from" is taken.

### System configuration

**Rails version**: tested inside 6.0.3.2

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Other configurations**: ActionMailer::Base.default_options from set to anything

**Comment by everton** [comment]
It seems that this was something made by intent at cb05880bbe88ca1ac2dade1e15dac8bd9be33cc9

> https://github.com/smartinez87/exception_notification/commit/cb05880bbe88ca1ac2dade1e15dac8bd9be33cc9#diff-d4c1ad5564dad0953ccdef5f08228841R130

Is this an error or this behavior changed? How can I keep using my configured e-mail as the sender instead of the default one?

**Comment by smartinez87** [comment]
hi @everton, thanks for reporting the issue!

You are correct, the behavior was changed by mistake. A new version was just released (4.4.2) that fixes it.

**Comment by everton** [comment]
I tested it here the 4.4.2 and it still not working for me.

**Comment by smartinez87** [comment]
@everton Analyzed the change and decided to remove the code introduced, so new version (4.4.3) should work as before.

**Comment by everton** [comment]
Thank you @smartinez87, it is working properly in 4.4.3
