### ISSUE TITLE
link in the readme IS NOT AVAILABLE

### ISSUE THREAD

**Issue by yshmarov** [smartinez87/exception_notification#508]
![image](https://user-images.githubusercontent.com/13472945/118407738-4a17a780-b682-11eb-8eec-c0c4abca85eb.png)
![image](https://user-images.githubusercontent.com/13472945/118407742-526fe280-b682-11eb-8c3e-9a9a72c19c9a.png)

**Comment by smartinez87** [comment]
should be fixed now, thanks!
