### ISSUE TITLE
Additional data doesn't show in teams notification

### ISSUE THREAD

**Issue by rachitpant** [smartinez87/exception_notification#515]
### Expected behavior
Additional data passed in `request.env["exception_notifier.exception_data"]` should be shown in the team channel notification within the Data section.

### Actual behavior
This does not happen. This bug is similar to #490 but for teams.

### System configuration
**Rails version**:
6.1.4.1
**Ruby version**:
2.6.3

**Comment by jakefrancis** [comment]
Is this library still active @smartinez87?

@rachitpant opened a fix for this a year and a half ago.  https://github.com/smartinez87/exception_notification/pull/516

This fix would be extremely useful.

**Comment by smartinez87** [comment]
hi @jakefrancis, I have merged the PR as it solves the issue.
