### ISSUE TITLE
How to not ignore default ignored exceptions 

### ISSUE THREAD

**Issue by AlexandreK38** [smartinez87/exception_notification#60]
Hi, 
I am using the 2.5.2 version of the gem, but I want to have mails for all the exceptions I can have. I could not find how to remove the default ignored exceptions, as RoutingError for example.
How can we do that ?
Thanks,
Alex

**Comment by jacobjlevine** [comment]
Hey @smartinez87, this is definitely still an issue. I think the problem is the below method. It makes it impossible to ever get notifications for the default ignored exceptions.

```ruby
def ignored_exception?(ignore_array, exception)
  (Array(ignored_exceptions) + Array(ignore_array)).map(&:to_s).include?(exception.class.name)
end
```
