### ISSUE TITLE
Email sending with Resque

### ISSUE THREAD

**Issue by kanfet** [smartinez87/exception_notification#98]
It is possible to send notifications with Resque?

**Comment by fpenapita** [comment]
@kanfet @DouweM Have you been able to get exception_notification send notifications mails using Resque?

I have tried it using something like this:
```
config.add_notifier :email, {
    :mailer_parent        => 'ResqueMailer',
    :email_prefix         => "[PREFIX] ",
    :sender_address       => 'from@example.com',
    :exception_recipients => ['to@example.com']
  }
```

where ResqueMailer is defined like this:
```
class ResqueMailer < ActionMailer::Base
  include Resque::Mailer
end
```

But with this configuration I am getting the following error:
```
An error occurred when sending a notification using 'email' notifier. SystemStackError: stack level too deep
```

**Comment by qaswm** [comment]
Looking for something similar.
